# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  
 #Free tier eligible linux t2.micro image
 Vagrant.configure("2") do |config|
     config.vm.box = "dummy"
     config.vm.provider :aws do |aws, override|
         aws.access_key_id = "AKIAJITUDUXTVN43MXVA"
         aws.secret_access_key = "nL1/fzfuPbwCKtk3p53hln6uleQH84+8Fs/DOQ37"
         aws.region = "ap-southeast-1"            
         aws.keypair_name = "usha-key-pair-sng"
         #aws.security_groups = [“your_security_group_here”]
         aws.security_groups =["usha-sg-singapore"]
         aws.ami="ami-c9b572aa"
         aws.instance_type = "t2.micro"
         override.ssh.private_key_path = "../usha-key-pair-sng.pem"
         override.ssh.username = "ec2-user"
	end
end